services:
  - type: private_service
    name: mysql
    env: docker
    plan: free
    autoDeploy: false
    dockerfilePath: ./mysql.Dockerfile

  - type: web
    name: wordpress
    env: docker
    plan: free
    autoDeploy: false
    dockerfilePath: ./Dockerfile  
    envVars:
      - key: WORDPRESS_DB_HOST
        value: mysql 
      - key: WORDPRESS_DB_USER
        value: wordpress
      - key: WORDPRESS_DB_PASSWORD
        value: strongpassword
      - key: WORDPRESS_DB_NAME
        value: wordpress
